
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userservice
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 4844



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
